USER_NAME: Amr_Maged_Local

ID: 55_21247

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task03db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCBzaWduaW5n
  expiration: 3600000

server:
  port: 8080
